### ISSUE TITLE
Issue when start to download or install.

### ISSUE THREAD

**Issue by Heimdall4n6** [digitalsleuth/WIN-FOR#2] opened 2023-06-20 15:28 UTC
I have an issue on a new win 11 machine and VM.
Requirements already installed but error message .

Send you log file
[winfor-customizer-output-20230620-051832.log](https://github.com/digitalsleuth/WIN-FOR/files/11802200/winfor-customizer-output-20230620-051832.log)

**Comment by digitalsleuth** [comment] 2023-06-20 15:46
This appears to be an issue with the System.Security permissions management. I'll take a look this afternoon, but in the meantime you can try deleting the C:\winfor-temp folder and the contents of the salt directory at C:\ProgramData\Salt Project\Salt\srv\salt and try again.

Cheers!

**Comment by Heimdall4n6** [comment] 2023-06-20 16:06
thank you for your answer.
done deltion but same issue.

**Comment by digitalsleuth** [comment] 2023-06-20 20:34
@Heimdall4n6 when you ran the download or install commands, did you select a different user other than the one currently logged in?

**Comment by Heimdall4n6** [comment] 2023-06-20 20:40
yes indeed.
i didn't understand that you had to enter the user name of the active windows session.
I'll try tomorrow and let you know the result.
thanks again

**Comment by digitalsleuth** [comment] 2023-06-20 20:42
You do not have to enter the current logged in user, I'm just trying to narrow down the cause of the issue. The tool is intended to create the entered user if it does not currently exist, and install tools and configuration for that user. It appears that the issue may possibly be related to that option. 

I'm working on it now and will get back to you once I have a resolution :)

**Comment by digitalsleuth** [comment] 2023-06-21 01:48
@Heimdall4n6 Could you send me the winfor-saltstack*.log file so I can identify a bit better what the cause of the issue is? I've tried to duplicate the issue but without success.

**Comment by Heimdall4n6** [comment] 2023-06-21 09:08
can tou tell me where i can find this

**Comment by digitalsleuth** [comment] 2023-06-21 12:50
This is located at the root of the C drive.

**Comment by Heimdall4n6** [comment] 2023-06-22 08:29
[winfor-customizer-output-20230622-102731.log](https://github.com/digitalsleuth/WIN-FOR/files/11830975/winfor-customizer-output-20230622-102731.log)
Hi,

This is the only log file i have found.

**Comment by digitalsleuth** [comment] 2023-06-22 11:56
Thanks for checking. I'm still working on duplicating the issue, but no luck yet. Can you provide me with the following information?
- Version of Windows 11 you're using, including the edition (Home, Pro, Enterprise etc)
- Is this system joined to a domain?
- If joined to a domain, are you executing as a local admin or domain admin?
- When entering the username to create, does it contain any spaces or non-alphanumeric characters?

Cheers

**Comment by Heimdall4n6** [comment] 2023-06-22 12:02
no problem:

win 11 pro last release.
no domain

on one the username have a space and on the over numbers.

I had also thought about the problem of spaces in the user name, which is known to cause problems with command lines, but the 2nd user name doesn't have spaces but has numbers.

thank you again

**Comment by digitalsleuth** [comment] 2023-06-22 13:33
I think I have an idea of what might be causing the issue. Can you possibly create a new folder (doesn't matter the name or location), then right-click on the folder and select Properties. From there, click on the Security tab. Once there, can you take a screenshot and attach it here?

**Comment by Heimdall4n6** [comment] 2023-06-22 13:35
î’m not at work now can i do this tomorrow ?

**Comment by digitalsleuth** [comment] 2023-06-22 13:39
Of course. Cheers!

**Comment by Heimdall4n6** [comment] 2023-06-23 14:55
this is the screenshot of settings from security tab of a new folder
![Capture d'écran 2023-06-23 165346](https://github.com/digitalsleuth/WIN-FOR/assets/137196768/993010ed-d8b8-4263-bbf3-f426d752f81d)

**Comment by digitalsleuth** [comment] 2023-06-23 15:18
Okay, looks like I was right in my thought process. In few separate locations in my code ([here](https://github.com/digitalsleuth/WIN-FOR/blob/bee537005480b4d6beab270dcbacce5b8f6b474a/WinFOR-Customizer/MainWindow.xaml.cs#L869C22-L869C22) and [here](https://github.com/digitalsleuth/WIN-FOR/blob/bee537005480b4d6beab270dcbacce5b8f6b474a/WinFOR-Customizer/MainWindow.xaml.cs#L1257) for example), I've made the assumption that the FileSystemAccessRule should apply to the "Users" group, enforcing the English word as a static value. Since you're working on a French system, the "Users" group is actually "Utilisateurs", and these sections are failing.

I'm going to try to re-work this in a better manner so as to adapt to other languages for this method and these functions. Thanks for bringing this to my attention!

**Comment by Heimdall4n6** [comment] 2023-06-23 16:06
no problem thank you again i ´m waiting for news from you … take your time.
thank you again.

**Comment by digitalsleuth** [comment] 2023-06-23 20:50
Hi @Heimdall4n6 , I've generated a test Release Candidate for you to try out to see if this resolves your issue. If so, I'll make final adjustments and push a proper release. You can download the new, self-contained installer [here](https://github.com/digitalsleuth/WIN-FOR/releases/tag/v7.1.0-rc1).

**Comment by digitalsleuth** [comment] 2023-07-02 00:41
Hi @Heimdall4n6 , have you had a chance to download and try the release candidate to see if this fixes your issue?

**Comment by Heimdall4n6** [comment] 2023-07-03 13:08
Hi,

i was able to test the rc version but unfortunately i still have the same problem.

i will try to test on an english windows version.

**Comment by digitalsleuth** [comment] 2023-07-04 02:48
Hi @Heimdall4n6 , I've managed to recreate the error and am working on a solution for this now. It does have to do with the language of the system, but I think it's slightly more subtle and specific than that. I'll keep you posted on the progress.

**Comment by Heimdall4n6** [comment] 2023-07-04 12:04
Hello,

thank you very much for your feedback.
I'm glad you were able to reproduce the error and that it may be useful to you.
i'm waiting for the corrected version so i can test it.
thank you.

**Comment by digitalsleuth** [comment] 2023-07-04 18:04
Hi @Heimdall4n6 , I've managed to fix the issue, but I haven't packaged the fix yet. I'm refactoring some of the code to be a bit more name-compliant. I'll upload the fixed version in a few hours once I get back to my computer.

**Comment by digitalsleuth** [comment] 2023-07-06 18:37
Hi @Heimdall4n6 , I haven't forgotten about you. I've fixed and packaged the application, but haven't uploaded it yet, since I realized that the same issues regarding language also exist in the current Salt States, and wouldn't necessarily apply the same way on your system. I didn't want to have you try the application only for it to fail, so I'm finishing testing on the new Salt States, then will upload both the new States and new application.

I appreciate your patience, and will again let you know when it's all ready!

**Comment by Heimdall4n6** [comment] 2023-07-06 18:44
Hello,

no problem with deadlines i understand completely.
thank you very much for the work done to solve the problem.
i'm looking forward to testing your program which will help me prepare pc's or windows vm's for forensic analysis.

good luck to you and thanks again

**Comment by digitalsleuth** [comment] 2023-07-09 02:46
Hi @Heimdall4n6 , I've just uploaded the newest release, and have tested this and the associated Salt States over several days in a Windows 11 French (France) environment. Everything seems to be working well with both the application and the states.

Please let me know if this resolves the issue. Cheers!

**Comment by digitalsleuth** [comment] 2023-07-14 13:46
Hi @Heimdall4n6 , have you had a chance to try this to see if your issues are resolved?

**Comment by Heimdall4n6** [comment] 2023-07-14 16:03
Hi,
I'm currently on vacation but I'm going to ask some colleagues to try it out and let me know the results if you agree.

**Comment by digitalsleuth** [comment] 2023-07-27 23:21
Hi @Heimdall4n6 , I know you might still be on vacation, but on the chance that you're not, I just wanted to follow-up on this to see if you or your colleagues have had a chance to try this out.

Cheers!

**Comment by digitalsleuth** [comment] 2023-08-08 14:44
@Heimdall4n6 Can you try again and see if you get the same result? Sometimes the hashes can be incorrect if the download didn't quite complete or was cut off.

**Comment by digitalsleuth** [comment] 2023-08-08 16:33
I wasn't at a computer for my last response but I just confirmed that the hashes were, in fact, different for some reason. I just released a new version (no changes, just the version number) and the hashes match now. IF you try again, you shouldn't have any issues.

**Comment by Heimdall4n6** [comment] 2023-08-08 16:39
i will try tomorrow.

thank you again

**Comment by Heimdall4n6** [comment] 2023-08-09 14:54
> This appears to be an issue with the System.Security permissions management. I'll take a look this afternoon, but in the meantime you can try deleting the C:\winfor-temp folder and the contents of the salt directory at C:\ProgramData\Salt Project\Salt\srv\salt and try again.
> 
> Cheers!

**Comment by Heimdall4n6** [comment] 2023-08-09 14:55
Hi,

I did a new install.
The instance is completed with errors.
I did not have time to control but i think some programs are missing.
Isend you all logs.

Thank you
[winfor-customizer-output-20230809-013126.log](https://github.com/digitalsleuth/WIN-FOR/files/12304026/winfor-customizer-output-20230809-013126.log)
[winfor-customizer-output-20230809-120449.log](https://github.com/digitalsleuth/WIN-FOR/files/12304027/winfor-customizer-output-20230809-120449.log)
[winfor-saltstack-v2023.21.5.log](https://github.com/digitalsleuth/WIN-FOR/files/12304028/winfor-saltstack-v2023.21.5.log)

**Comment by digitalsleuth** [comment] 2023-08-15 17:12
Hi @Heimdall4n6 , sorry for the delay, but I've been away on vacation. Can you confirm for me that the path `C:\ProgramData\Salt Project\Salt\conf` exists on your system, and if the file `minion` exists in that directory?

**Comment by Heimdall4n6** [comment] 2023-08-21 10:11
sorry for delay,

Yes the path exist and also the minion file inside

**Comment by digitalsleuth** [comment] 2023-08-23 02:26
Hi @Heimdall4n6 , I'm unable to duplicate the error you encountered. Would you perhaps be able to uninstall SaltStack from your current Windows installation, then attempt the WIN-FOR installation or download process again?

**Comment by digitalsleuth** [comment] 2023-09-06 02:36
Hi @Heimdall4n6 , please let me know if you've managed to try the suggestion above. If not, you can also try using the latest release (v8.2.0) to see if this assists in resolving the issue.

**Comment by Heimdall4n6** [comment] 2023-09-10 07:02
hi,

sorry I've been busy, I'll try the new version as soon as possible and get back to you.

**Comment by digitalsleuth** [comment] 2023-10-04 22:38
Hi @Heimdall4n6 , since it's been a while, I'm going to close this issue. However, if you continue to have this same issue, please let me know. If anything else comes up, please open a new Issue.

Cheers!

**Closed by digitalsleuth** 2023-10-04 22:38 UTC

**Comment by Heimdall4n6** [comment] 2023-10-08 07:00
Hello,
I'm sorry but lately I've been too busy to run new tests.
I seem to have sent you the logs of my last test during which everything seemed to be installed but there were 2 errors.
When I've run some more tests, I'll let you know if there were any problems.
bravo for your work.
